apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "prometheus.rules"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets:
              - localhost:9090

      - job_name: 'traefik-external'
        metrics_path: /metrics
        static_configs:
          - targets:
              - traefik-metrics-external.ingress.svc.cluster.local:8082

      - job_name: 'traefik-internal'
        metrics_path: /metrics
        static_configs:
          - targets:
              - traefik-metrics-internal.ingress.svc.cluster.local:8082