apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins

      containers:
      - name: jenkins
        image: jenkins/jenkins:2.571

        ports:
        - containerPort: 8080
        - containerPort: 50000

        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

      - name: docker
        image: docker:28-cli
        command:
        - sleep
        - infinity

        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock

      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home

      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket