apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default
  labels:
    app: cloudflared

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloudflared

  template:
    metadata:
      labels:
        app: cloudflared

    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.3.0
          imagePullPolicy: IfNotPresent

          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(CLOUDFLARE_TUNNEL_TOKEN)

          env:
            - name: CLOUDFLARE_TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-token
                  key: token
            - name: DNS_RESOLVERS
              value: "1.1.1.1,8.8.8.8"

          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

      restartPolicy: Always