apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-env
  namespace: vaultwarden
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "sasasaasas"
  AWS_SECRET_ACCESS_KEY: "sasasaassaassasaas"
  AWS_REGION: "eu-west-1"
  S3_BUCKET: "secrets-and-backups"
  RETENTION_DAYS: "14"