apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: internal-registry
type: Opaque
stringData:
  registry-http-secret: gjkashfsjhkfasjhkgkhlgsjkasf
  username: admin
  password: changeme
  htpasswd: |
    admin:$2y$05$...