networks:
  macvlan_net:
    external: true

  proxy:
    external: true

  dashboards:
    external: true

  internal:
    external: true


services:
  traefik:
    image: traefik:v3.7.9
    container_name: traefik
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    env_file:
      - .env

    command:
      - "--configFile=/traefik.yml"

    ports:
      # Do NOT bind these on the host anymore.
      # macvlan gives Traefik its own LAN IP.
      # Access via 192.168.1.98:80/443
      - "8080:8080"

    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
      - ./logs:/var/log/traefik
      - ./plugins:/plugins-local:ro

    networks:
      macvlan_net:
        ipv4_address: 192.168.1.98

      dashboards:

      internal:

      proxy:


    labels:

      # Enable Traefik provider
      - "traefik.enable=true"


      # ==========================
      # Main Traefik Dashboard
      # ==========================

      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_INTERNAL_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

      - "traefik.http.routers.traefik.service=api@internal"

      - "traefik.http.routers.traefik.middlewares=auth"

      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"


      # ==========================
      # Dashboard Aggregator
      # ==========================

      - "traefik.http.routers.dashboard.rule=Host(`dashboard.local.xboy.me`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

      - "traefik.http.routers.dashboard.service=noop@internal"


      # ==========================
      # Wildcard certificate domains
      # ==========================

      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=${WILDCARD_DOMAIN}"