apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
type: Opaque
data: #base64 encoded
  ADMIN_TOKEN: "YWRtaW4tYXNnanNhYXNqaC1zamFzaGhrYXNoa3NhamsK"
  POSTGRES_USER: "YWRtaW4K"
  POSTGRES_PASSWORD: "YWRtaW4K"
  POSTGRES_DB: "YWRtaW4K"