services:
  adguardhome:
    image: adguard/adguardhome:v0.107.78
    container_name: adguardhome
    restart: unless-stopped
    networks:
      pihole_macvlan: # check ~/setup-macvlan.sh or in git
        ipv4_address: 192.168.1.98   # Choose an unused IP in your LAN
      internal:
    volumes:
      - ./work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Moscow

networks:
  internal:
    external: true
  pihole_macvlan:
    external: true
